/* Generated by WSDL Java Compiler. Please do not edit this file. NetcoolGatewayWriter.java Version : 5.1 */
package com.o2.techm.netcool.eai.o2gateway.netcool.wsdl;

import java.rmi.RemoteException;


/**
 * com.o2.o2gateway.netcool.wsdl.NetcoolGatewayWriter
 */
public interface NetcoolGatewayWriter extends java.rmi.Remote {

    /**
     * netcool_connect.
     * 
     * @param aClient (Reference)
     * @return boolean
     * @throws NetcoolGatewayProcessEventFailure_Exception  (NetcoolGatewayProcessEventFailure_Exception)
     */
    public boolean netcool_connect(NetcoolGatewayGatewayClient aClient) throws NetcoolGatewayProcessEventFailure_Exception, RemoteException;

    /**
     * sendEvent.
     * 
     * @param aEvent (NetcoolGatewayNetcoolEvent)
     * @return boolean
     * @throws NetcoolGatewayProcessEventFailure_Exception  (NetcoolGatewayProcessEventFailure_Exception)
     */
    public boolean sendEvent(NetcoolGatewayNetcoolEvent aEvent) throws NetcoolGatewayProcessEventFailure_Exception, RemoteException;

    /**
     * deregister.
     * 
     * @param aClient (Reference)
     * @return boolean
     * @throws NetcoolGatewayProcessEventFailure_Exception  (NetcoolGatewayProcessEventFailure_Exception)
     */
    public boolean deregister(NetcoolGatewayGatewayClient aClient) throws NetcoolGatewayProcessEventFailure_Exception, RemoteException;

}
