/* Generated by WSDL Java Compiler. Please do not edit this file. NetcoolGatewayReaderEvent.java Version : 5.1 */
package com.o2.techm.netcool.eai.o2gateway.netcool.wsdl;



/**
 * com.o2.o2gateway.netcool.wsdl.NetcoolGatewayReaderEvent.
 */
public class NetcoolGatewayReaderEvent {

    /**
     * Target namespace of Schema in which this type is defined.
     */
    public static final String TARGET_NAMESPACE = "http://ps.iona.com/artix/o2/NetcoolGateway.wsdl";

    /**
     * QName of the type.
     */
    public static final javax.xml.namespace.QName QNAME = null;


    private NetcoolGatewayNetcoolEvent aEvent;


    /**
     * getAEvent.
     * 
     * @return NetcoolGatewayNetcoolEvent
     */
    public NetcoolGatewayNetcoolEvent getAEvent() {
        return aEvent;
    }

    /**
     * setAEvent.
     * 
     * @param val (NetcoolGatewayNetcoolEvent)
     */
    public void setAEvent(NetcoolGatewayNetcoolEvent val) {
        this.aEvent = val;
    }

    /**
     * Returns the qname of the object.
     * @return javax.xml.namespace.QName the qname of the object.
     */
    public javax.xml.namespace.QName _getQName() {
        return QNAME;
    }

    /**
     * Returns a string representation of the object.
     * @return String a string representation of the object.
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();
        if (aEvent != null) {
            buffer.append("aEvent : " + aEvent + "\n");
        }
        return buffer.toString();
    }
}
