/* Generated by WSDL Java Compiler. Please do not edit this file. NetcoolGatewayEventType.java Version : 5.1 */
package com.o2.techm.netcool.eai.o2gateway.netcool.wsdl;



/**
 * com.o2.o2gateway.netcool.wsdl.NetcoolGatewayEventType.
 */
public class NetcoolGatewayEventType {

    /**
     * Target namespace of Schema in which this type is defined.
     */
    public static final String TARGET_NAMESPACE = "http://ps.iona.com/artix/o2/NetcoolGateway.wsdl";

    /**
     * QName of the type.
     */
    public static final javax.xml.namespace.QName QNAME = new javax.xml.namespace.QName("http://ps.iona.com/artix/o2/NetcoolGateway.wsdl", "NetcoolGateway.EventType");

    private final String _val;

    /**
     * enum value newET.
     */
    public static final String _newET = "newET";
    /**
     * enum type newET.
     */
    public static final com.o2.techm.netcool.eai.o2gateway.netcool.wsdl.NetcoolGatewayEventType newET = new com.o2.techm.netcool.eai.o2gateway.netcool.wsdl.NetcoolGatewayEventType(_newET);

    /**
     * enum value updateET.
     */
    public static final String _updateET = "updateET";
    /**
     * enum type updateET.
     */
    public static final com.o2.techm.netcool.eai.o2gateway.netcool.wsdl.NetcoolGatewayEventType updateET = new com.o2.techm.netcool.eai.o2gateway.netcool.wsdl.NetcoolGatewayEventType(_updateET);

    /**
     * enum value journalET.
     */
    public static final String _journalET = "journalET";
    /**
     * enum type journalET.
     */
    public static final com.o2.techm.netcool.eai.o2gateway.netcool.wsdl.NetcoolGatewayEventType journalET = new com.o2.techm.netcool.eai.o2gateway.netcool.wsdl.NetcoolGatewayEventType(_journalET);

    /**
     * enum value closeET.
     */
    public static final String _closeET = "closeET";
    /**
     * enum type closeET.
     */
    public static final com.o2.techm.netcool.eai.o2gateway.netcool.wsdl.NetcoolGatewayEventType closeET = new com.o2.techm.netcool.eai.o2gateway.netcool.wsdl.NetcoolGatewayEventType(_closeET);


    /**
     * Constructs a new enumeration with specified value.
     * @param value String.
     */
    protected NetcoolGatewayEventType(String value) {
        _val = value;
    }

    /**
     * Get Value of this enumeration.
     * @return String value of enumeration.
     */
    public String getValue() {
        return _val;
    };

    /**
     * Constructs an enumeration from specified value.
     * @param value String value of enumeration.
     * @return com.o2.o2gateway.netcool.wsdl.NetcoolGatewayEventType enumeration type.
     */
    public static com.o2.techm.netcool.eai.o2gateway.netcool.wsdl.NetcoolGatewayEventType fromValue(String value) {
        if (value.equals(_newET)) {
            return newET;
        }
        if (value.equals(_updateET)) {
            return updateET;
        }
        if (value.equals(_journalET)) {
            return journalET;
        }
        if (value.equals(_closeET)) {
            return closeET;
        }
        throw new IllegalArgumentException("Invalid enumeration value: "+value);
    };

    /**
     * Constructs an enumeration from String.
     * @param value String value of enumeration.
     * @return com.o2.o2gateway.netcool.wsdl.NetcoolGatewayEventType enumeration type.
     */
    public static com.o2.techm.netcool.eai.o2gateway.netcool.wsdl.NetcoolGatewayEventType fromString(String value) {
        if (value.equals("newET")) {
            return newET;
        }
        if (value.equals("updateET")) {
            return updateET;
        }
        if (value.equals("journalET")) {
            return journalET;
        }
        if (value.equals("closeET")) {
            return closeET;
        }
        throw new IllegalArgumentException("Invalid enumeration value: "+value);
    };

    /**
     * Returns the qname of the object.
     * @return javax.xml.namespace.QName the qname of the object.
     */
    public javax.xml.namespace.QName _getQName() {
        return QNAME;
    }

    /**
     * Returns a string representation of the object.
     * @return String a string representation of the object.
     */
    public String toString() {
        return ""+_val;
    }

}
