/* Generated by WSDL Java Compiler. Please do not edit this file. NetcoolGatewayWriterSendEventResult.java Version : 5.1 */
package com.o2.techm.netcool.eai.o2gateway.netcool.wsdl;



/**
 * com.o2.o2gateway.netcool.wsdl.NetcoolGatewayWriterSendEventResult.
 */
public class NetcoolGatewayWriterSendEventResult {

    /**
     * Target namespace of Schema in which this type is defined.
     */
    public static final String TARGET_NAMESPACE = "http://ps.iona.com/artix/o2/NetcoolGateway.wsdl";

    /**
     * QName of the type.
     */
    public static final javax.xml.namespace.QName QNAME = null;


    private boolean _return;


    /**
     * is_return.
     * 
     * @return boolean
     */
    public boolean is_return() {
        return _return;
    }

    /**
     * set_return.
     * 
     * @param val (boolean)
     */
    public void set_return(boolean val) {
        this._return = val;
    }

    /**
     * Returns the qname of the object.
     * @return javax.xml.namespace.QName the qname of the object.
     */
    public javax.xml.namespace.QName _getQName() {
        return QNAME;
    }

    /**
     * Returns a string representation of the object.
     * @return String a string representation of the object.
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();
        buffer.append("_return : " + _return + "\n");
        return buffer.toString();
    }
}
