/* Generated by WSDL Java Compiler. Please do not edit this file. NetcoolGatewayGatewayClient.java Version : 5.1 */
package com.o2.techm.netcool.eai.o2gateway.netcool.wsdl;

import java.rmi.RemoteException;


/**
 * com.o2.o2gateway.netcool.wsdl.NetcoolGatewayGatewayClient
 */
public interface NetcoolGatewayGatewayClient extends java.rmi.Remote {

    /**
     * takeEvents.
     * 
     * @param aEvent (NetcoolGatewayNetcoolEvent)
     */
    public void takeEvents(NetcoolGatewayNetcoolEvent aEvent) throws RemoteException;

}
