
package com.o2.techm.netcool.eai.o2gateway.remedy.webservice;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HPD_IncidentInterface_NETCOOL_WSPortTypePortType", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HPDIncidentInterfaceNETCOOLWSPortTypePortType {


    /**
     * 
     * @param notes
     * @param incidentType
     * @param errorCode
     * @param className
     * @param ciName
     * @param workInfoNote
     * @param resolutionCategorizationTier2
     * @param resolutionCategorizationTier1
     * @param urgency
     * @param resolutionCategorizationTier3
     * @param contact
     * @param action
     * @param company
     * @param serverSerial
     * @param incidentID
     * @param locked
     * @param ciType
     * @param contactMethod
     * @param summary
     * @param alarmSeverity
     * @param assignedGroup
     * @param impact
     * @param productCategorizationTier3
     * @param workInfoSummary
     * @param alarmFirstOccurence
     * @param externalTicketID
     * @param priority
     * @param errorMsg
     * @param classID
     * @param service
     * @param workInfoType
     * @param operationalCategorizationTier2
     * @param alarmKey
     * @param operationalCategorizationTier1
     * @param parameters
     * @param status
     * @param customer
     * @param operationalCategorizationTier3
     */
    @WebMethod(operationName = "Incident_SubmitAddWI_Service", action = "urn:TGTUK_NETCOOL_HPD_WS/Incident_SubmitAddWI_Service")
    @RequestWrapper(localName = "Incident_SubmitAddWI_Service", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS", className = "com.o2.osiris.web.webservices.remedy.client.InputMapping1")
    @ResponseWrapper(localName = "Incident_SubmitAddWI_ServiceResponse", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS", className = "com.o2.osiris.web.webservices.remedy.client.OutputMapping1")
    public void incidentSubmitAddWIService(
        @WebParam(name = "Action", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String action,
        @WebParam(name = "Status", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS", mode = WebParam.Mode.INOUT)
        Holder<StatusType> status,
        @WebParam(name = "Company", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String company,
        @WebParam(name = "Customer", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String customer,
        @WebParam(name = "Summary", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String summary,
        @WebParam(name = "Notes", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String notes,
        @WebParam(name = "Service", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String service,
        @WebParam(name = "Impact", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        ImpactType impact,
        @WebParam(name = "Urgency", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        UrgencyType urgency,
        @WebParam(name = "Incident_Type", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        IncidentTypeType incidentType,
        @WebParam(name = "Operational_Categorization_Tier_1", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String operationalCategorizationTier1,
        @WebParam(name = "Operational_Categorization_Tier_2", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String operationalCategorizationTier2,
        @WebParam(name = "Operational_Categorization_Tier_3", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String operationalCategorizationTier3,
        @WebParam(name = "Resolution_Categorization_Tier_1", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String resolutionCategorizationTier1,
        @WebParam(name = "Resolution_Categorization_Tier_2", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String resolutionCategorizationTier2,
        @WebParam(name = "Resolution_Categorization_Tier_3", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String resolutionCategorizationTier3,
        @WebParam(name = "CI_Name", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String ciName,
        @WebParam(name = "CI_Type", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String ciType,
        @WebParam(name = "Product_Categorization_Tier_3", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String productCategorizationTier3,
        @WebParam(name = "Contact_Method", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String contactMethod,
        @WebParam(name = "Contact", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String contact,
        @WebParam(name = "External_Ticket_ID", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String externalTicketID,
        @WebParam(name = "ServerSerial", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String serverSerial,
        @WebParam(name = "Alarm_First_Occurence", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        XMLGregorianCalendar alarmFirstOccurence,
        @WebParam(name = "Incident_ID", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS", mode = WebParam.Mode.INOUT)
        Holder<String> incidentID,
        @WebParam(name = "Work_Info_Summary", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String workInfoSummary,
        @WebParam(name = "Work_Info_Note", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String workInfoNote,
        @WebParam(name = "Work_Info_Type", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        WorkInfoTypeType workInfoType,
        @WebParam(name = "Locked", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        LockedType locked,
        @WebParam(name = "Assigned_Group", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS", mode = WebParam.Mode.INOUT)
        Holder<String> assignedGroup,
        @WebParam(name = "Class_ID", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        Integer classID,
        @WebParam(name = "Class_Name", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String className,
        @WebParam(name = "Alarm_Key", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        String alarmKey,
        @WebParam(name = "Alarm_Severity", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS")
        Integer alarmSeverity,
        @WebParam(name = "errorCode", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS", mode = WebParam.Mode.OUT)
        Holder<String> errorCode,
        @WebParam(name = "errorMsg", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS", mode = WebParam.Mode.OUT)
        Holder<String> errorMsg,
        @WebParam(name = "Priority", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS", mode = WebParam.Mode.OUT)
        Holder<PriorityType> priority,
        @WebParam(name = "AuthenticationInfo", targetNamespace = "urn:TGTUK_NETCOOL_HPD_WS", header = true, partName = "parameters")
        AuthenticationInfo parameters);

}
